image: kroniak/ssh-client

stages:
  - pull
  - build
  - deploy
  - clear

variables:
  DISCORD_WEBHOOK: "https://discord.com/api/webhooks/1121384915179683840/7Gjtm9YjTv6tgyN3yYzOID0JC3esk59aaau5rZ5YtHkScg7UgGp0vSexDZ4KsgV10GzO"

before_script:
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" > ~/id_rsa
  - chmod 400 ~/id_rsa
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add
  - apk update
  - apk add curl

on_failure:
  stage: .post
  script:
    - >
      curl -X POST -H "Content-Type: application/json" -d '{
        "content": "$STAGE_NAME stage failed: '\''$CI_JOB_NAME'\'' ('\''$CI_JOB_ID'\'')",
        "username": "CI/CD Pipeline",
        "avatar_url": "https://cdn-icons-png.flaticon.com/512/5950/5950864.png"
      }' $DISCORD_WEBHOOK

git-pull:
  stage: pull
  script:
    - ssh -i "~/id_rsa" -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd booking && git checkout $CI_COMMIT_BRANCH && git pull origin $CI_COMMIT_BRANCH"
  only:
    - master

build:
  stage: build
  script:
    - ssh -i "~/id_rsa" -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd booking && docker build -t admin-web ."
  needs:
    - job: git-pull
      optional: true
  only:
    - master

  when: on_success

deploy:
  stage: deploy
  script:
    - ssh -i "~/id_rsa" -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd booking && docker rm -f admin-web && docker run -d --network=booking -p 80:80 --name admin-web admin-web"
    - >
      curl -X POST -H "Content-Type: application/json" -d '{
        "content": "Deploy stage completed '$CI_JOB_NAME' ('$CI_JOB_ID')",
        "username": "CI/CD Pipeline",
        "avatar_url": "https://cdn0.iconfinder.com/data/icons/round-ui-icons/512/tick_green.png"
      }' $DISCORD_WEBHOOK
  only:
    - master
  when: on_success

clear:
  stage: clear
  script:
    - ssh -i "~/id_rsa" -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker system prune -f"
  only:
    - master
  needs:
    - job: deploy
      optional: true
  when: on_success
